name: mijn_tank_app
description: Een moderne tank en kilometer registratie app.
publish_to: 'none'
version: 1.0.74+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  confetti: ^0.7.0

  # State management
  provider: ^6.1.1
  
  # Database & Opslag
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.1
  path_provider: ^2.1.2

  # Functionaliteit (Backup/Export)
  share_plus: ^10.1.0
  file_picker: ^8.1.2
  csv: ^6.0.0
  intl: ^0.20.2

  # Grafieken (Versie afgestemd op jouw code)
  fl_chart: ^1.1.1
  
  # Iconen
  cupertino_icons: ^1.0.2

  # Google (Aanwezig op verzoek, maar niet actief in main om crashes te voorkomen)
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  googleapis_auth: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true